repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
  - repo: local
    hooks:
      - id: prettier-docker
        name: prettier (docker)
        entry: bash -c 'docker run --rm -v "$(pwd):/work" -w /work ghcr.io/tiagovla/oiseau-prettier:latest --write $@' --
        language: system
        types_or: [css, javascript, html, astro]
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
