name: Deploy to GitHub Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Run Python script with CouchDB environment variables
        env:
          COUCHDB_HOST: ${{ secrets.COUCHDB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          COUCHDB_USER: ${{ secrets.COUCHDB_USER }}
          COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
        run: python .github/tools/fetch_data.py
      - name: Install, build, and upload your site
        uses: withastro/action@v3
  cleanup:
    name: Cleanup old deployments
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: github-pages
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
